### PR TITLE
bump npmVersion from 5.8.0 to 6.0.1

### PR DESCRIPTION
**Pull request by vorburger**

### CODE REVIEW

**Comment by vorburger** [comment]
@edewit is this a good idea? I thought of it because of this on the CLI, which is NOK for me:

```
 npm start

> minecraft-js2@0.0.1 start /home/vorburger/dev/Minecraft/git/minecraft-storeys-maker/scratch
> npm run server:dev


> minecraft-js2@0.0.1 server:dev /home/vorburger/dev/Minecraft/git/minecraft-storeys-maker/scratch
> webpack-dashboard -- webpack-dev-server --config ./webpack.config.js --hot --inline --progress --watch --open



   ╭─────────────────────────────────────╮
   │                                     │
   │   Update available 5.6.0 → 6.0.1    │
   │       Run npm i npm to update       │
   │                                     │
   ╰─────────────────────────────────────╯

$ npm -v
5.6.0

$ npm i npm
npm WARN minecraft-js2@0.0.1 No repository field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

+ npm@6.0.1
added 682 packages in 15.585s

$ npm -v
5.6.0
```

**Comment by vorburger** [comment]
@edewit I'm guessing the 2 additional commits for `package.json` and `package-lock.json` should go with this?

**Comment by vorburger** [comment]
@edewit I've just rebased this, and applied it to scratch3/ as well - OK for you if I merge this?

**Comment by edewit** [comment]
:+1:

**Pull request merged**
