### PR TITLE
use Vert.x RPC service code generation, initial version (fixes #53)

### LINKED ISSUE #53: use Vert.x RPC service code generation
to replace current event bus messaging related code

### PR DESCRIPTION
**Pull request by vorburger**

### CODE REVIEW

**Comment by vorburger** [comment]
@edewit have a closer look over (and manually test?) all of this whenvever you have some time, and lemme know when you think this is good to go into master for you also / when you need it to build on top of it for Scratch v3...

PS: Do you want to build new PR(s) on top of this to also convert, step by step, at least the 'ping', 'narrate' and `command` (but I'm a little less clear about `registerCondition`, and think `login` will perhaps disappear with #41) from `ch.vorburger.minecraft.storeys.web.ActionsConsumer` into the new `ch.vorburger.minecraft.storeys.api.Minecraft` API and `ch.vorburger.minecraft.storeys.api.impl.MinecraftImpl` - I expect `ActionsConsumer` will get thinner and thinner, and eventually probably completely disappear?

**Comment by edewit** [comment]
okay had some problems starting the `SeleniumTest` as a java app because the generated classes where not found, but it works!

**Comment by vorburger** [comment]
@edewit "it works" meaning just SeleniumTest, or manual test title in Scratch v2/Flash? Good to merge?

**Comment by edewit** [comment]
good to merge

**Pull request merged**
