### PR TITLE
added Typescript and jasmine

### PR DESCRIPTION
**Pull request by edewit**

### CODE REVIEW

**Comment by edewit** [comment]
@vorburger no longer a work in progress now even builds the javascript with gradle

**Comment by vorburger** [comment]
Question: How did you see us using this from ScratchX? Because we used to be able to just have it open the JS directly from GitHub... with this change, we replace the minecraft.js by a src/index.ts which we build into JS... and [basically break this ScratchX URL](https://github.com/vorburger/minecraft-storeys-maker/commit/0fc2d1c43f310c6062da6f1e45b87d8d52fb91d6#diff-977fc8a6b75bc6be84e1c5a269bc51d7R44) - worth a quick discussion? (Perhaps I should also document how one actually uses this at this point! :smile:)

Also do we actually currently use lodash, or are you planning soon, or could that be removed, to simplify?

**Comment by edewit** [comment]
I think a great way to still do this is by creating a release and adding the binary there something like this: https://github.com/edewit/repo/releases/tag/v1 for example. And we should remove this url from this constant.

**Comment by vorburger** [comment]
OK. I'm not actually clear how one creates such releases (manually?), but let's take that up in https://github.com/vorburger/minecraft-storeys-maker/issues/13 and not hold this up. Give me a little bit of time to locally test this change, then I'll merge it ASAP!

**Comment by edewit** [comment]
I did this one manually, but I'm sure somebody created a script for this. we could use something like this: https://github.com/riiid/gradle-github-plugin

**Comment by vorburger** [comment]
finally, merged!

**Pull request closed without merging**
