### PR TITLE
bump Gradle

### PR DESCRIPTION
**Pull request by vorburger**

### CODE REVIEW

**Comment by vorburger** [comment]
@edewit FYI in another PR I was trying to build a container of all this without S2I and on Java 11 instead of 8, and wasn't getting very far, Gradle wouldn't even start in the build container (likely "just" related to Java 11 instead of 8), so I started looking into a Gradle version upgrade here... fixed one Gradle Plugin, now it's stuck here, which is more in your area of expertise:

```
> Task :api:npmBuildProd FAILED

FAILURE: Build failed with an exception.

* What went wrong:
A problem was found with the configuration of task ':api:npmBuildProd'.
> File '/home/vorburger/Kubernetes/Minecraft/minecraft-storeys-maker/api/webpack.config.js' specified for property '$3' does not exist.
```

**Comment by edewit** [comment]
Right this isn't a problem with the gradle bump or the java version change. I changed from webpack to rollup a while ago seems that with the new version of gradle the check is "better" anyway I changed it and now I get hit a problem with the annotation processor not running or something

**Comment by edewit** [comment]
@vorburger why would we want java 11? I think minecraft server only supports java 8

**Comment by edewit** [comment]
My small fix is here #196 this PR can now be closed

**Pull request closed without merging**
